"""Add multi-project support

Revision ID: cba1119ddd25
Revises: 6ac58a01aabf
Create Date: 2026-01-29 07:50:52.069225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba1119ddd25'
down_revision = '6ac58a01aabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create projects table
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Step 2: Insert default project for existing data
    from datetime import datetime
    op.execute(
        f"""
        INSERT INTO projects (id, name, description, created_at, updated_at)
        VALUES (1, 'Default Project', 'Initial project for PRD management', '{datetime.utcnow()}', '{datetime.utcnow()}')
        """
    )

    # Step 2b: Reset the sequence so next insert uses id=2
    op.execute("SELECT setval('projects_id_seq', (SELECT MAX(id) FROM projects))")

    # Step 3: Add project_id column as nullable first (to handle existing categories)
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))

    # Step 4: Set all existing categories to project_id = 1 (default project)
    op.execute("UPDATE categories SET project_id = 1 WHERE project_id IS NULL")

    # Step 5: Make project_id NOT NULL now that all rows have values
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('project_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_categories_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key, index, and project_id column from categories
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categories_project_id'))
        batch_op.drop_column('project_id')

    # Drop projects table (will cascade delete default project)
    op.drop_table('projects')
    # ### end Alembic commands ###
